#!/usr/bin/env bash
# Usage: %COMMAND%
# Summary: Example of auto completion for files
# Help: This is an example of auto completion for files

# provide subdue completions
if [[ $1 == '--complete' ]]; then
    echo -l -h
    exit 0
fi
echo "ls"
